com:
  andreidodu:
    minerva-europass:
      templates-directory: "templates"
      basic-template-directory: "basic"
      basic-template-name: "basic-resume.xsl"
      image-path: /your/path/here
      enable-summary: true
      enable-summary-results-tech-years-experience: true
      enable-summary-results-tech-frequency: true
      max-summary-results-tech-years-experience: 10
      max-summary-results-tech-frequency: 10
      max-number-top-back-end-technologies: 5
      show-top-back-end-technologies: false
      max-number-top-front-end-technologies: 5
      show-top-front-end-technologies: false
