spring:
  mvc:
    dispatch-options-request: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/minerva
    username: postgres
    password: postgres
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        default_schema: public
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/database/db.changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
server:
  port: 8081
com:
  andreidodu:
    minerva-europass:
      templates-directory: "templates"
      basic-template-directory: "basic"
      basic-template-name: "basic-resume.xsl"
      image-path: /your/path/here
      enable-summary: true
      enable-summary-results-tech-years-experience: true
      enable-summary-results-tech-frequency: true
      max-summary-results-tech-years-experience: 10
      max-summary-results-tech-frequency: 10
      max-number-top-back-end-technologies: 5
      show-top-back-end-technologies: false
      max-number-top-front-end-technologies: 5
      show-top-front-end-technologies: false
